apiVersion: apps/v1
kind: Deployment
metadata:
  name: swagger-ui
spec:
  replicas: 1
  selector:
    matchLabels:
      app: swagger-ui
  template:
    metadata:
      labels:
        app: swagger-ui
    spec:
      containers:
        - name: swagger-ui
          image: swaggerapi/swagger-ui
          ports:
            - containerPort: 8080
          env:
            - name: URL
              value: http://coupon-app:8080/v3/api-docs
---
apiVersion: v1
kind: Service
metadata:
  name: swagger-ui
spec:
  type: NodePort
  selector:
    app: swagger-ui
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 30081